import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// Import the Web3Provider
import { Web3Provider } from "@/lib/web3"; // Remove the extra semicolon
import WalletConnectButton from "@/components/ui/WalletConnectButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Web3Provider> {/* Use uppercase W and P */}
          <WalletConnectButton /> 
          {children}
        </Web3Provider> {/* Use proper closing tag, not self-closing */}
      </body>
    </html>
  );
}